name: Issues Workflow

on:
  issues:
    types: [opened, edited, closed, reopened]

env:
  ISSUE_BODY: ${{ github.event.issue.body }}
  ISSUE_NUMBER: ${{ github.event.issue.number }}
  ISSUE_TITLE: ${{ github.event.issue.title }}
  WORKFLOW_URL: ${{ secrets.WORKFLOW_URL }}

jobs:      
  issue_created:
    name: Issue Created
    if: ${{ github.event_name == 'issues' && github.event.action == 'opened' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo $ISSUE_BODY
          echo $ISSUE_NUMBER
          echo $ISSUE_TITLE
          
  issue_edited:
    name: Issue Edited
    env:
      WORKFLOW_URL: ${{ secrets.WORKFLOW_URL }}
    if: ${{ github.event_name == 'issues'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo $ISSUE_BODY
          echo $ISSUE_NUMBER
          echo $ISSUE_TITLE