name: Issues Workflow

on:
  issues:
    types: [opened, edited, closed, reopened]

jobs:      
  github:
    name: github
    if: ${{ github.event_name == "issues" && github.event.action == "edited" }}
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "$GITHUB_CONTEXT"