name: Issues Workflow

on:
  issues:
    types: [opened, edited, closed, reopened]

jobs:      
  issue_created:
    name: Issue Created
    if: ${{ github.event_name == 'issues' }} && {{ github.event.action == 'opened' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "Issue was created"

  issue_edited:
    name: Issue Edited
    if: ${{ github.event_name == 'issues' }} && {{ github.event.action == 'edited' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "Issue was edited"