name: Issues Workflow

on:
  issues:
    types: [opened, edited, closed, reopened]

env:
  ISSUE_ACTION: ${{ github.event.action }}
  ISSUE_BODY: ${{ github.event.issue.body }}
  ISSUE_NUMBER: ${{ github.event.issue.number }}
  ISSUE_TITLE: ${{ github.event.issue.title }}
  ISSUE_URL: ${{ github.event.issue.html_url }}
  WORKFLOW_URL: ${{ secrets.WORKFLOW_URL }}

jobs:      
  issue_created:
    name: Issue Created
    if: ${{ github.event_name == 'issues' && github.event.action == 'opened' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo $ISSUE_BODY
          echo $ISSUE_NUMBER
          echo $ISSUE_TITLE
          
  issue_edited:
    name: Issue Edited
    env:
      WORKFLOW_URL: ${{ secrets.WORKFLOW_URL }}
    if: ${{ github.event_name == 'issues'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
        curl --silent --location --request POST "$WORKFLOW_URL" \
        --header 'Accept: application/json' \
        --header 'Content-Type: text/plain' \
        --data-raw "{
            "action": "$ISSUE_ACTION"
            "body" : "$ISSUE_BODY"
            "number" : "$ISSUE_NUMBER"
            "title" : "$ISSUE_TITLE"
            "url" : "$ISSUE_URL"
        }"