name: Issues Workflow

on:
  issues:
    types: [opened, edited, closed, reopened]

jobs:
  issue_creation:
    name: Issue Created
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
        echo ${{github.event}}
        echo ${{github.event_path}}
        echo ${{github.ref}}

  # issue_updated:
  #   name: Issue Updated
  #   if: github.event.issues == "edited"
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - run: echo "Issue was Updated"